services:
  n8n:
    image: n8nio/n8n
    user: "1000:1000"
    container_name: n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/data/database.sqlite
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=1234567890xxx
      - GENERIC_TIMEZONE=Asia/Shanghai
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./n8n/data:/data
      - ./uploads:/srv/uploads
    networks:
      - n8n-network
    depends_on:
      - caddy
  python-ai:
    image: ghcr.io/geekpii/document-extraction-ai_web-dev:latest
    container_name: container_python_ai_booking_v2
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      TZ: Etc/GMT+8
      V2_AI_ENV: /run/secrets/booking_v2_ai_env
    secrets:
      - booking_v2_ai_env
    ports:
      - "8001:8001"
    networks:
      - qc_v2_network_dev
    volumes:
      - ./srv/document-extraction:/srv/document-extraction
      - ./srv/booking_v2:/code/booking_v2
    command: ["sh", "-c", "poetry run fastapi dev main.py --host 0.0.0.0 --port 8001"]
  caddy:
    build:
        context: ./caddy
        dockerfile: Dockerfile
    container_name: container_caddy
    environment:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
        TZ: Etc/GMT+8
    networks:
        - n8n-network
    ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
    volumes:
        - caddy_data:/data
        - caddy_config:/config
        - ./uploads:/srv/uploads
networks:
  n8n-network:
    driver: bridge
volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
